### PR TITLE
Support ExportNamedDeclarations

### LINKED ISSUE #4: ExportNamedDeclaration throws unknown error
ExportNamedDeclarations, eg:
```js
export class pureComponent extends React.Component {
  static propTypes = {
    className: React.PropTypes.string.isRequired
  };

  render() {
    return (
      <div className={this.props.className}>
        Transformed JSX String
      </div>
    );
  }
}
```
babel-plugin-react-pure-components throws:
```js
unknown: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
```
please see: https://astexplorer.net/#/Q13PK25kdL/11 for replicated **error state**
please see: https://astexplorer.net/#/Q13PK25kdL/12 for **working example** of `export default class`

any ideas? i'm having trouble tracing the error above or which node it's coming from. as usual, any guidance is greatly appreciated and i'm happy to make changes if you steer me in the right direction. 

thank you!

### PR DESCRIPTION
**Pull request by justingreenberg**
resolves #4 until we can figure out what’s going on

https://astexplorer.net/#/Q13PK25kdL/13

### CODE REVIEW

**Comment by justingreenberg** [comment]
@thejameskyle are you inclined to wait on this?

**Comment by thejameskyle** [comment]
There's two separate issues that this brought up that I want to get figured out. Sorry for not moving faster

**Comment by justingreenberg** [comment]
no worries, i kinda figured and i know you're busy. if you could reference the issues here that would be awesome :)  for tracking but mostly just to try to understand at lowest possible level. thanks again!

**Comment by thejameskyle** [comment]
https://phabricator.babeljs.io/T6994
https://phabricator.babeljs.io/T6995

**Pull request closed without merging**
